### ISSUE TITLE
Connection not released causing scala app to hang

### ISSUE THREAD

**Issue by scalame** [ScalaConsultants/reactive-rabbit#16]
The rabbitmq connection is never closed/released after shutting down the actor system and requires an explicit interruption from the user to exit the app

**Comment by mkiedys** [comment]
There are two ways of solving this problem:
1) auto closing after last subscriptions gets canceled
2) explicit `close` method in `Connection`

Which one do you prefer?

**Comment by scalame** [comment]
May I suggest another solution:
Exposing the classes/objects under the `impl` package. I found myself needing to extend `ExchangeSubscriber` so that I log messages that were not published to the queue. With this possible solution one can also cast a `Connection` to `RabbitMqConnection` to explicitly close the connection to rabbitmq

**Comment by mkiedys** [comment]
Can you describe what you wanted to extend `ExchangeSubscriber`? Would be interesting to know what is your usage pattern for that.
