### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by Ciaran0** [ScalaConsultants/reactive-rabbit#24]
Better documentation would be good.
Such things as how to set config vars, settings available etc.
I would be willing to help.

Thanks

**Comment by mkiedys** [comment]
I like the idea. What parts of the library in your opinon should be covered first?
Do you thunk that putting documentation in README.md is good enough?
Let me know if you have any other ideas of preferences.

**Comment by OElesin** [comment]
Starting from the basics is not a bad idea. As stated by @Ciaran0 setting config, publishing a message.
