### ISSUE TITLE
Publisher handling server failure

### ISSUE THREAD

**Issue by pocman** [ScalaConsultants/reactive-rabbit#45]
Hi,
how can I make a `QueuePublisher` resilient to server failure ?
I'm creating a Stream using `Source.fromPublisher(connection.consume(queue = queue))` and I would like to make this source resilient to rabbitMQ (server side) failure. 
I tried using 
```
  val resumingLogging: Supervision.Decider = {
    case sig: ShutdownSignalException =>
      Logger.warn(s"${sig.getCause}\n${sig.getMessage}\n${sig.getStackTrace.mkString("\n")}")
      Supervision.Restart
```
But it doesn't do the trick.

**Comment by pocman** [comment]
Adding more configuration did the trick.
```
  automatic-recovery = true

  recovery-interval = 2s
```

**Comment by mkiedys** [comment]
👍
