### ISSUE TITLE
Use custom SslContext?

### ISSUE THREAD

**Issue by etspaceman** [ScalaConsultants/reactive-rabbit#50]
We use a custom SslContext when using RabbitMQ. I noticed that this library only allows for the standard SslContext to be used, provided a protocol string. It would be really nice to be able to pass a custom context into the constructor. 

I'm effectively forced to extend the Connection trait and employ the custom SslContext in the interim.

**Comment by LGLO** [comment]
If you are able to prepare PR, I would take care of merging it.
My proposal is to:
1. rename `ssl` to `sslProtocol` in `ConnectionSettings`.
1. add `sslContext: Option[javax.net.ssl.SSLContext]` to `ConnectionSettings`, default `None`.
1. In `Conversions` first use `sslContext` to invoke `factory.useSslContext(SSLContext)` and if `sslContext` is None then use `sslProtocol` to invoke `factory.useSslContext(String)`
I would not like to touch parsing config, if you get your `ConnectionSettings` from parsing config file, then I leave user with `s.copy(sslContext = ...)`.

**Comment by etspaceman** [comment]
@LGLO PR Created:

https://github.com/ScalaConsultants/reactive-rabbit/pull/51

**Comment by mkiedys** [comment]
Merged.
