### ISSUE TITLE
Scala 2.12 build

### ISSUE THREAD

**Issue by liff** [ScalaConsultants/reactive-rabbit#56]
Should be straightforward, I think, but currently blocked by nbronson/scala-stm#48.

**Comment by mkiedys** [comment]
Yap. We need Scala STM.

**Comment by liff** [comment]
scala-stm [0.8 for 2.12](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22scala-stm_2.12%22) is now on Maven Central.

**Comment by mkiedys** [comment]
Done.

```Scala
libraryDependencies += "io.scalac" %% "reactive-rabbit" % "1.1.4"
```
